# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [2]:
import itertools
for comb in itertools.combinations(['A','B',"C"],2):
    print(comb)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [3]:
count = 1
for item in itertools.cycle(['Python', 'is', 'fun']):
    print(item)
    if count==10:
        break
    else:
        count+=1

Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [19]:
import glob
import glob
for python in glob.glob('*.py'):
    print(python)


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [32]:
from bs4 import BeautifulSoup
def get_text(html):
    soup = BeautifulSoup(html, 'html.parser')
    p = soup.find('p')
    if p:
        return p.get_text()
    else:
        return None
html = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"
get_text(html)


'AI is transforming the world'

**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [7]:
import re
def replace_AI(text):
    return re.sub("AI","Artificial Intelligence",text)
    
text = "AI is transforming the world"
replace_AI(text)
    

'Artificial Intelligence is transforming the world'

**CP6**: Create a numpy array of 10 zeros.

In [20]:
import numpy as np
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**CP7** Create a numpy array of the integers from 10 to 49.

In [21]:
ten_49 = np.arange(10,50)
ten_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [22]:
mat = np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

## why machine learning models require large amounts of data?
#### Machine learning models have millions of parameters. These parameters are instrumental in enabling the model to achieve precision. The model acquires these parameters during the training process, which involves training it with a large amount of data.
## What does it mean for an amount of data to be large?
#### A large amount of data refers to a diverse dataset that contains a sufficient quantity of data to generate all the required parameters for the model.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

#### 1. Discrimination: AI systems can exhibit discrimination or bias if the training data provided is itself biased. To prevent this, it is essential to train the AI system using a diverse and representative dataset that includes data from all relevant parties or groups.
#### 2. AI can be used for hacking: Hackers may use AI techniques to penetrate in to a system and launch sophisticated attacks. To prevent this, robust security measures, AI-enabled defense systems, continuous monitoring, and ethical AI use should be implemented. Collaboration and information sharing among cybersecurity professionals are essential for staying ahead of emerging AI-based hacking threats